### ISSUE TITLE
Add workflow to auto publish the extension to chrome web store

### ISSUE THREAD

**Issue by phenixcoder** [phenixcoder/feature-flags-chrome-plugin#5]
Using this action:
```yaml
uses: Klemensas/chrome-extension-upload-action@$VERSION
with:
  refresh-token: 'xxxxxxxxxxxxxxxxxxxxxx'
  client-id: 'xxxxxxxxxxxxx'
  client-secret: 'xxxxxxxxxxxx'
  file-name: './extension.zip'
  app-id: 'xzc12xzc21cx23'
  publish: true
```

The workflow should check some sort of test before build. Upon successful build, creates a new version using `semantic-release`. If version is bumped, then publishes the extension to chrome web store.

- [ ] Test / Validate.
- [ ] Version Bump check.
- [ ] If version bumped, the push to chrome web store.
